name: NeemaGospel CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo, pdo_mysql

    - name: Install Composer
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate key
      run: php artisan key:generate

    - name: Run tests
      run: php artisan test

#  Deployment step for production

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #   - name: Deploy to VPS
  #     uses: appleboy/ssh-action@v1.0.0
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USER }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       script: |
  #         cd /var/www/neemagospel-app
  #         git pull origin main
  #         composer install --no-dev --optimize-autoloader
  #         php artisan migrate --force
  #         php artisan config:cache
  #         php artisan route:cache


  